name: Trakt Integration Continuous Deployment

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  cd:
    runs-on: ubuntu-latest
    steps:
      - name: Create release note
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
        run: |
          gh release create "$tag" \
              --repo="$GITHUB_REPOSITORY" \
              --title="${GITHUB_REPOSITORY#*/} ${tag#v}" \
              --generate-notes