"""Constants for the Trakt integration."""

DOMAIN = "trakt_tv"

API_HOST = "https://api.trakt.tv"
OAUTH2_AUTHORIZE = "https://trakt.tv/oauth/authorize"
OAUTH2_TOKEN = f"{API_HOST}/oauth/token"

TMDB_HOST = "http://api.tmdb.org"
TMDB_TOKEN = "0eee347e2333d7a97b724106353ca42f"

LANGUAGE_CODES = [
    "ab",
    "aa",
    "af",
    "ak",
    "sq",
    "am",
    "ar",
    "an",
    "hy",
    "as",
    "av",
    "ay",
    "az",
    "bm",
    "ba",
    "eu",
    "be",
    "bn",
    "bi",
    "nb",
    "bs",
    "bg",
    "my",
    "ca",
    "km",
    "ch",
    "ce",
    "ny",
    "zh",
    "kw",
    "co",
    "cr",
    "hr",
    "cs",
    "da",
    "dv",
    "nl",
    "dz",
    "en",
    "eo",
    "et",
    "fo",
    "fj",
    "fi",
    "fr",
    "ff",
    "gd",
    "gl",
    "lg",
    "ka",
    "de",
    "el",
    "gn",
    "gu",
    "ht",
    "ha",
    "he",
    "hi",
    "hu",
    "is",
    "ig",
    "id",
    "ie",
    "iu",
    "ik",
    "ga",
    "it",
    "ja",
    "jv",
    "kl",
    "kn",
    "ks",
    "kk",
    "rw",
    "ky",
    "kg",
    "ko",
    "ku",
    "lo",
    "la",
    "lv",
    "li",
    "ln",
    "lt",
    "lb",
    "mk",
    "mg",
    "ms",
    "ml",
    "mt",
    "mi",
    "mr",
    "mh",
    "mn",
    "nv",
    "ne",
    "se",
    "no",
    "nn",
    "oc",
    "oj",
    "or",
    "om",
    "os",
    "pi",
    "pa",
    "fa",
    "pl",
    "pt",
    "ps",
    "qu",
    "ro",
    "rm",
    "ru",
    "sm",
    "sg",
    "sa",
    "sc",
    "sr",
    "sn",
    "ii",
    "sd",
    "si",
    "sk",
    "sl",
    "so",
    "st",
    "es",
    "su",
    "sw",
    "ss",
    "sv",
    "tl",
    "ty",
    "tg",
    "ta",
    "tt",
    "te",
    "th",
    "bo",
    "ti",
    "to",
    "ts",
    "tn",
    "tr",
    "tk",
    "tw",
    "ug",
    "uk",
    "ur",
    "uz",
    "vi",
    "cy",
    "fy",
    "wo",
    "xh",
    "yi",
    "yo",
    "za",
    "zu",
]

# Default values
DEFAULT_LANGUAGE = "en"
DEFAULT_UPDATE_INTERVAL = 15  # minutes
DEFAULT_DAYS_TO_FETCH = 90
DEFAULT_MAX_MEDIAS = 5

# Config keys
CONF_UPDATE_INTERVAL = "update_interval"
CONF_LANGUAGE = "language"
CONF_SENSORS = "sensors"
S_LIST = "lists"

# Sort options
LIST_SORT_BY_DEFAULT = [
    {"value": "rank", "label": "Rank"},
    {"value": "added", "label": "Added"},
    {"value": "title", "label": "Title"},
    {"value": "released", "label": "Released"},
    {"value": "runtime", "label": "Runtime"},
    {"value": "popularity", "label": "Popularity"},
    {"value": "random", "label": "Random"},
    {"value": "percentage", "label": "Percentage"},
    {"value": "my_rating", "label": "My Rating"},
    {"value": "watched", "label": "Watched"},
    {"value": "collected", "label": "Collected"},
]
LIST_SORT_BY_VIP = [
    {"value": "imdb_rating", "label": "IMDB Rating"},
    {"value": "tmdb_rating", "label": "TMDB Rating"},
    {"value": "rt_tomatometer", "label": "Rotten Tomatoes Tomatometer"},
    {"value": "rt_audience", "label": "Rotten Tomatoes Audience"},
    {"value": "metascore", "label": "Metascore"},
    {"value": "votes", "label": "Votes"},
    {"value": "imdb_votes", "label": "IMDB Votes"},
    {"value": "tmdb_votes", "label": "TMDB Votes"},
]
LIST_SORT_BY_CUSTOM = [
    {"value": "rating", "label": "Rating"},
]
LIST_SORT_ORDER = [
    {"value": "asc", "label": "Ascending"},
    {"value": "desc", "label": "Descending"},
]
LIST_MEDIA_TYPES = [
    {"value": "any", "label": "Any"},
    {"value": "movie", "label": "Movie"},
    {"value": "show", "label": "Show"},
]
